USE_REQUEST_TRANSPORT_TYPE = True
DISABLE_SSL_WARNINGS = True
SUPPORTED_SUDS_VERSION = 0.7
LOCAL_TIME_ZONE='Europe/London'
AUTOTASK_API_TIMEZONE = 'US/Eastern'
AUTOTASK_API_BASE_URL = 'https://webservices.autotask.net/atservices/1.5/atws.wsdl'
AUTOTASK_API_QUERY_RESULT_LIMIT = 500
AUTOTASK_API_QUERY_ID_LIMIT = 200
AUTOTASK_API_ENTITY_SEND_LIMIT = 200

WRAPPER_DISABLE_CLEAN_ENTITIES = False